spring:
  application:
    name: credOperations-1
    
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: MySQL9150.@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
